---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: my-deploy
  labels: 
    app: my-app 
spec:   
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3 
      maxUnavailable: 1  
  replicas: 3 
  selector:  
    matchLabels: 
      app: my-app
    matchExpressions: 
      - {key: app, operator: In, values: [my-app]}
  template:
    metadata: 
      name: my-pod
      labels: 
        app: my-app
        env: devops 
    spec: 
      containers: 
        - name: nginx 
          image: nginx 
          ports:
          - name: http 
            containerPort: 80
...
---    
apiVersion: v1 
kind: Service 
metadata: 
  name: my-svc-node
  labels: 
    app: my-svc-node
    env: devops
spec:
  type: NodePort
  selector:
    app: my-app
  ports: 
    - name: http
      protocol: TCP 
      port: 80
      targetPort: 80       
...
