apiVersion: v1 
kind: Pod
metadata: 
  name: mypod
  labels: 
    app: myapp
    env: devops
spec:
  containers:
    - name: nginx
      image: nginx 
      ports: 
        - name: http
          containerPort: 80
